version: '3'

services:
  flask-app:
    image: bhargavbaggam01/simple-form-app:latest
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root@123
      - MYSQL_DATABASE=form_app
      - REDIS_HOST=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  mysql:
    image: bhargavbaggam01/simple-form-app:latest-sql
    ports:
      - "3307:3306"
    environment:
          MYSQL_ROOT_PASSWORD: Root@123
          MYSQL_DATABASE: form_app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRoot@123"]
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: